package im.wilk.jsonitem.item;

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import im.wilk.jsonitem.item.factory.JsonItemFactory;
import im.wilk.jsonitem.item.factory.JsonItemFactoryBuilder;
import im.wilk.jsonitem.item.model.JsonDataItem;
import im.wilk.jsonitem.item.model.JsonListItem;
import im.wilk.jsonitem.item.model.JsonStructItem;
import im.wilk.jsonitem.item.model.PathParserConfig;
import im.wilk.jsonitem.item.node.JsonPathNode;

import java.math.BigDecimal;
import java.util.List;

public abstract class JsonItem implements
        JsonListItem<JsonItem>,
        JsonStructItem<JsonItem>,
        JsonDataItem<JsonItem> {

    /**
     * Current type of item. ANY - means not specified yet.
     *
     */
    public enum ItemType {
        DATA,
        LIST,
        STRUCT,
        ANY
    }

    /**
     * Return ItemType of given item.
     *
     * @return one of enumerated values.
     */
    public abstract ItemType getItemType();

    /**
     * Return item from specific path.
     * Item doesn't have to exist in underlying jsonElement and will not be created
     * until set(...) method is called.
     *
     * Path can represent multiple nested levels of data hierarchy.
     *
     * Path format definition depends on parser settings from JsonItemFactoryBuilder.
     *
     * E.g. expression:
     *    root.get("top").get("list").get(1).get(3).get("data")
     *
     *  can be entered directly as:
     *   when using pathWithSlashAndColon() (standard)
     *    root.get("top/list:1:3/data")
     *
     *   when using pathWithDotAndBrackets()
     *    root.get("top.list[1][3].data")
     *
     * @param path - path in specific format
     * @return JsonItem referencing to specific node in data hierarchy.
     * throws
     *  PathParsingException - when path is invalid (@see PathParsingException)
     * @throws
     *  IllegalStateException - if lenientStructure is disabled and node wasn't of type LIST
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disabled and index in path is greater than (last allocated + 1)
     *
     *  default behaviour is not to throw only PathParsingException and always return valid JsonItem.
     */
    public abstract JsonItem get(String path);

    /**
     * Alternative way of accessing item in data hierarchy using directly list of JsonPathNode objects.
     * this list may be generated by direct call to JsonPathParser.toNodes() or build manually.
     *
     * @param paths list of nodes
     * @return same as get(path)
     */
    public abstract JsonItem get(List<JsonPathNode> paths);

    /**
     * Return JsonItem describing item from list.
     * List doesn't have to exist in underlying ion structure.
     *
     * @param idx 0-based index of list
     * @return JsonItem referencing to specific node in data hierarchy
     * @throws
     *  IllegalStateException - if lenientStructure is disabled and node wasn't of type LIST
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index is greater than (last allocated + 1)
     *
     * default - no exception is thrown, list is allocated up to index and filled with nulls.
     */
    public abstract JsonItem get(int idx);

    /**
     * Set item in list with copy of content from other item.
     *
     * @param idx 0-based index of list
     * @param other JsonItem referencing to specific node in data hierarchy
     * @throws
     *  IllegalStateException - if lenientStructure is disabled and node wasn't of type LIST
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index is greater than (last allocated + 1)
     *
     * default - no exception is thrown, list is allocated up to index and filled with nulls.
     */
    public abstract void set(int idx, JsonItem other);

    /**
     * Add new item to list with copy of content from other item.
     *
     * @param other JsonItem referencing to specific node in data hierarchy
     * @throws
     *  IllegalStateException - if lenientStructure is disabled and node wasn't of type LIST
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index is greater than (last allocated + 1)
     *
     *  default - no exception is thrown, list is allocated up to index and filled with nulls.
     */
    public abstract void add(JsonItem other);

    /**
     * Set (replace if present) item with copy of content from other item.
     *
     * it will use alias (if set in path) or name of item from 'other' item.
     * if 'other' is item from list it will use name of list.
     *
     * @param other JsonItem referencing to specific node in data hierarchy
     */
    public abstract void set(JsonItem other);

    /**
     * Set (replace if present) item specific value.
     * Path can represent multiple  nested levels of data hierarchy.
     *
     * It's a short form of setting data. It has same effect as .get(path).set(value)
     *
     * @param path - path describing position in hierarchy.
     * @param value - value to be set
     * throws
     *  PathParsingException - when path is invalid
     * @throws
     *  IllegalStateException - if lenientStructure is disabled path enforces change of data hierarchy.
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index in path is greater than (last allocated + 1)
     *
     *  default - no exception is thrown.
     */
    public abstract void set(String path, String value);

    /**
     * Set (replace if present) item specific value.
     * Path can represent multiple  nested levels of data hierarchy.
     *
     * It's a short form of setting data. It has same effect as .get(path).set(value)
     *
     * @param path - path describing position in hierarchy.
     * @param value - value to be set
     * throws
     *  PathParsingException - when path is invalid
     * @throws
     *  IllegalStateException - if lenientStructure is disabled path enforces change of data hierarchy.
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index in path is greater than (last allocated + 1)
     *
     *  default - no exception is thrown.
     */
    public abstract void set(String path, Boolean value);

    /**
     * Set (replace if present) item specific value.
     * Path can represent multiple  nested levels of data hierarchy.
     *
     * It's a short form of setting data. It has same effect as .get(path).set(value)
     *
     * @param path - path describing position in hierarchy.
     * @param value - value to be set
     * throws
     *  PathParsingException - when path is invalid
     * @throws
     *  IllegalStateException - if lenientStructure is disabled path enforces change of data hierarchy.
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index in path is greater than (last allocated + 1)
     *
     *  default - no exception is thrown.
     */
    public abstract void set(String path, Number value);

    /**
     * Set (replace if present) item specific value.
     * Path can represent multiple  nested levels of data hierarchy.
     *
     * It's a short form of setting data. It has same effect as .get(path).set(value)
     *
     * @param path - path describing position in hierarchy.
     * @param value - value to be set
     * throws
     *  PathParsingException - when path is invalid
     * @throws
     *  IllegalStateException - if lenientStructure is disabled path enforces change of data hierarchy.
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index in path is greater than (last allocated + 1)
     *
     *  default - no exception is thrown.
     */
    public abstract void set(String path, BigDecimal value);

    /**
     * Set (replace if present) item with copy of content from other item.
     * Path can represent multiple nested levels of data hierarchy.
     *
     * It's a short form of setting data. It has same effect as .get(path).set(value)
     *
     * @param path - path describing position in hierarchy.
     * @param other JsonItem referencing to specific node in data hierarchy
     * throws
     *  PathParsingException - when path is invalid
     * @throws
     *  IllegalStateException - if lenientStructure is disabled path enforces change of data hierarchy.
     * @throws
     *  IndexOutOfBoundsException - if lenientLists is disable and index in path is greater than (last allocated + 1)
     *
     *  default - no exception is thrown.
     */
    public abstract void set(String path, JsonItem other);

    /**
     * Sets current item to null.
     * if item was referencing to struct or list entire content will be removed.
     */
    public abstract void setNull();

    /**
     * Removes current item from data hierarchy.
     * if item was referencing to struct or list entire content will be removed.
     */
    public abstract void remove();

    /**
     * For a list of paths returns a list of JsonItems.
     * It does not filter data in any way, so it may return items referencing to non-existent nodes.
     *
     * @param paths list of path expressions (@see get(name))
     * @return list of JsonItems
     * throws
     *  PathParsingException - when path is invalid
     */
    public abstract List<JsonItem> select(String... paths);

    /**
     * Returns JsonItem representing container of current item.
     *
     * @return Container or null when called for root item.
     */
    public abstract JsonItem getContainer();

    /**
     * Returns pathNode describing given item.
     *
     * @return pathNode describing given item.
     */
    public abstract JsonPathNode getPathNode();

    /**
     * Return full path of current item in format accepted by parser and get(name) method.
     *
     * @return full path
     */
    public abstract String getFullPath();

    /**
     *
     * @return
     *    Alias - if was defined in path
     *    Name of item in structure if item is part of structure
     *    Name of list if item is part of list
     *    "" (empty string) if it is a root item.
     */
    public abstract String name();

    /**
     * Returns a deep copy of underlying Json including any modifications performed.
     *
     * Items that refer to non-existing data in underlying ion will return JsonNull
     *
     * @return jsonElement data as described.
     */
    public abstract JsonElement asJsonElement();

    /**
     * Returns information about presence of given item in underlying Json structure.
     *
     * @return
     *    true - item exists in Json structure and is not null (it may be empty list/struct).
     *    flase - item doesn't exist in Json structure or is null.
     *
     */
    public abstract boolean exists();


    private static JsonItemFactory factory;
    private static JsonItemFactory getFactory() {
        if (factory == null) {
            factory = JsonItemFactoryBuilder.standard().withPathParserConfig(PathParserConfig.pathWithDotAndBrackets()).build();
        }
        return factory;
    }


    public static JsonItem from(String jsonString) {
        return getFactory().from(JsonParser.parseString(jsonString));
    }

    public static JsonItem from(JsonElement jsonElement) {
        return getFactory().from(jsonElement);
    }

    public static JsonItem empty() {
        return getFactory().empty();
    }

}
